apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: prod
  labels:
    app: demo-app
    environment: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: demo-app
        environment: prod
    spec:
      containers:
      - name: demo-app
        image: ghcr.io/srumonke/service-a:v4.1.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: 256Mi
            cpu: 150m
          limits:
            memory: 1Gi
            cpu: 1000m
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: SERVER_PORT
          value: '8080'
        - name: JAVA_OPTS
          value: -Xms512m -Xmx1536m
